# Generated by Django 3.1.4 on 2020-12-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=50)),
                ('high', models.FloatField(max_length=50)),
                ('low', models.FloatField(max_length=50)),
                ('close', models.FloatField(max_length=50)),
                ('volume', models.FloatField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
